### ISSUE TITLE
`AlertCondition.alertAfter` type should be string

### ISSUE THREAD

**Issue by kenfinnigan** [OpenSLO/OpenSLO#109]
### Summary

Currently the `alertAfter` field of `AlertCondition`, see [here](https://github.com/openslo/openslo#alert-condition) is defined as a `number` but the example uses `5m` as a value.

To cater for a value of `5m`, which is correct, the type should be `string`.

### What is the current *bug* behavior?

Type for `alertAfter` field set to `number`, but `5m` is an example value.

### What is the expected *correct* behavior?

Type for `alertAfter` field set to `string`.

### Possible fixes

Modify the type of `alertAfter` to be a string.

**Comment by kenfinnigan** [comment]
This also applies to `lookbackWindow` in `AlertCondition`

**Comment by programmer04** [comment]
Surpass by https://github.com/OpenSLO/OpenSLO/pull/93, the new type duration-shorthand has been introduced. Thanks for your involvement @kenfinnigan!
