### ISSUE TITLE
Allowed object name rules should be looser

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#118]
Current rules for names [are](https://github.com/OpenSLO/OpenSLO#general-schema):
* contain at most 63 characters
* contain only lowercase alphanumeric characters or -
* start with an alphanumeric character
* end with an alphanumeric character

When thinking about a large enough SLO management system (and considering how many object types the current spec supports), I propose giving a freer hand to implementers to make sure large systems can handle "namespacing" objects. Therefore the naming rules should imo change to something like this:

Implementations MUST support the following obj naming rules:
* contain at most 63 characters
* contain only lowercase alphanumeric characters or -
* start with an alphanumeric character
* end with an alphanumeric character

Implementations SHOULD additional support the following obj naming rules:
* contain up to 255 characters
* may contain the following special characters: `- . | / \`

**Comment by mmazur** [comment]
Actually just noticed the spec says "`name` _should_". That makes it an even better idea to provide more clarifications around this.

**Comment by ian-bartholomew** [comment]
I agree with this.  The limitation was initially set because of the history with the k8s spec, but as we are making this now, i think that its fine to expand this out.  It would be up to an implementation to handle ingesting an object name that is >63 characters, if they only support <63

**Comment by proffalken** [comment]
Also happy to support this.
