### ISSUE TITLE
Clarify SLO AlertPolicy 

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#133]
### Summary

In the [SLO](https://github.com/OpenSLO/OpenSLO#notes-slo) section, `alertPolicies` are not defined as being either inlined or a reference.  We should decide on one, and clarify it.

### What is the expected *correct* behavior?

Have in the spec if the `alertPolicies` in the `SLO` kind is a reference, inlined, or both.

**Comment by kenfinnigan** [comment]
It should align with the pattern for `Indicator`, `AlertCondition`, and `AlertNotificationTarget`. The `AlertPolicy` can be inlined or a reference
