### ISSUE TITLE
Add operator to Alert Condition 

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#140]
### Problem to solve

Right now, `spec.condition` doesn't have an operator (ie, "gt", "gte", "lt", etc) for the `threshold`.  We should add that in order to be more specific about the alerting.

**Comment by fearfactor3** [comment]
Created #167 for this enhancement.  Review at your leisure.

Prost! 🍺

**Comment by ian-bartholomew** [comment]
Thanks @fearfactor3 !

**Comment by fearfactor3** [comment]
This issue should be closed now.  It was merged into `main`.

**Comment by ian-bartholomew** [comment]
Closing per above
