### ISSUE TITLE
Add support for RatioTimeslices `budgetingMethod`

### ISSUE THREAD

**Issue by mmazur** [OpenSLO/OpenSLO#159]
There has been talk over the past ~year about a variation on the TimeSlices budgeting method that instead of treating each time slices as a pass/fail (1/0) value, uses their performance ratio (a float) as the input to the final SLO calculation. Initially this was called the WeightedTimeSlices Budgeting method, but I think Ratio is much more of a fitting name here. (Weights imply difference in importance and the point of Time Slices is that each slice has the same "weight" in the final calculation.)

This case is as a reference for tracking the work and any pre discussions we might want to have (a veto, anyone?). The PR will be fairly short, basically just this change:

```
  budgetingMethod: Occurrences | Timeslices | RatioTimeslices
```

and some dependencies, like making a note on `timeSliceTarget` that it's not used here.

**Comment by ian-bartholomew** [comment]
This makes sense to me :+1:

**Comment by proffalken** [comment]
Also happy with this, will find time to review the spec changes shortly
