### ISSUE TITLE
API Version should probably be v1alpha1 not v1alpha

### ISSUE THREAD

**Issue by brendandburns** [OpenSLO/OpenSLO#16]
The typical pattern in Kubernetes APIs is `v<eventual-version number> [alpha | beta ] < alpha/beta version number>`  e.g. `v1alpha1`

Without the additional version number it becomes impossible to revise the spec using semantic versioning.

e.g. `v1alpha1`, `v1alpha2`, etc.

Right now, you would have to do `v2alpha` or jump to `v1beta1` neither of which is probably desirable.

**Comment by ian-bartholomew** [comment]
Good call. After updating we should also update olso

**Comment by embano1** [comment]
Agreed and enforced in #32

**Comment by mmazur** [comment]
Closing as obsolete.
