### ISSUE TITLE
Question around `thresholdMetric` and its `budgetingMethod` calculation

### ISSUE THREAD

**Issue by vadasambar** [OpenSLO/OpenSLO#185]
Hi, sorry if these are silly questions. I am going through the README of https://github.com/OpenSLO/OpenSLO .
> **thresholdMetric** Metric, represents the query used for gathering data from metric sources. Raw data is used to compare objectives (threshold) values.
https://github.com/OpenSLO/OpenSLO#notes-sli
And I see our `target` in [Objectives](https://github.com/OpenSLO/OpenSLO#objectives) is always between 0 to 1 (1 not included)
1. Does this mean our `thresholdMetric` will always be between 0 to 1?
Under **budgetingMethod**
> Occurrences method uses a ratio of counts of good events to the total count of the events.
https://github.com/OpenSLO/OpenSLO#notes-slo
2. Does this mean if the `thresholdMetric` is above the set target or satisfies an operator like `> 90` (which can be specified with `op: gte` and `target: 0.9`), it is considered a good event and others are not? The good events contribute to `Occurrences` ratio in budgeting?

From OpenSLO slack thread: https://openslo.slack.com/archives/C0202J83M3R/p1667457148569529

**Comment by fpiwowarczyk** [comment]
I answered on slack to this question, if you will need help again please re-open this ticket.

**Comment by aaranmcguire** [comment]
Shame this was answered only in Slack, as I also wonder about this.

**Comment by fpiwowarczyk** [comment]
@aaranmcguire Shame on slack that it started to blure an old messages :D Thread was attached to issue, if I would know we won't be able to retrieve it later I would copy it in here too :P 

I will try to answer it again in here but need to return to the subject as it was over year ago.
