### ISSUE TITLE
Create a standard terms document

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#189]
### Problem to solve

There can be slightly different understandings of terms that we use, leading to misunderstanding and misalignment

### Proposal

Create a document that defines all the key term that this project uses.  ie Composite SLO, SLI, etc.

**Comment by fpiwowarczyk** [comment]
I think we should gather first batch of terms to dictionary to start working

**Comment by fpiwowarczyk** [comment]
Closing as it is implemented by #195
