### ISSUE TITLE
Define schema in .cue?

### ISSUE THREAD

**Issue by embano1** [OpenSLO/OpenSLO#20]
I think defining the schema using https://cuelang.org/ would bring a lot of benefits at this early stage of the project, e.g.:

- Simplified configuration/schema generation via flexible data and schema expression language
- Constrains, eg. bounds (numbers), optional/required/default fields, etc. 
- Import/export from/to standard formats, incl. CRD/OpenAPI

Related: https://github.com/OpenSLO/oslo/issues/23

**Comment by ian-bartholomew** [comment]
@embano1 I think that this is a really interesting idea. PRs are welcome for this if anyone wants to pick it up.  I think keeping them in this repo, for now, is fine, and we can move them into their own repo if we decide it's appropriate later.

Thanks!

**Comment by embano1** [comment]
@ian-bartholomew started working on a prototype schema as proposal. Will file PR once I have all fields covered.

**Comment by ian-bartholomew** [comment]
@embano1 thats amazing, thank you!

**Comment by embano1** [comment]
Created a WIP PR with couple of questions where I'm unclear about the SLO spec.

**Comment by ian-bartholomew** [comment]
@embano1 got it, thanks!

**Comment by nieomylnieja** [comment]
Since we've decided to go with Go structs for our source of truth I'm closing this issue. We'll probably end up generating JSON Schema from these structs as well, but any Cue effort is highly unlikely.
