### ISSUE TITLE
As a specification, will open SLO plan to be langage agnostic and easily integrable to any 3rd party program ?

### ISSUE THREAD

**Issue by soubinan** [OpenSLO/OpenSLO#216]
### Need the specification to be langage agnostic and easily integrable to any 3rd party program (I mean the CLI validation tool)

I know Go but all the projects I work on are not always in Go. How to use OSLO in Python, JS, Zig for example ?
I would like to integrate it in some projects we are working on to avoid any proprietary format and to be align with the standard everybody could selfdocument about and learn with a validation out of the box. How to do so ?

### Proposal

As a first step; to have OSLO as a Go package will be great ! but it is essential to have it on the more popular languages like Python, JS, Rust, Zig, Java ...

### Further details

For example, If I want to integrate our proprietary load testing tool with OSLO, how could we do it ?

**Comment by nieomylnieja** [comment]
the https://github.com/OpenSLO/oslo/releases/tag/v0.11.0 has just been created, you can now use it in your Go projects, to see an example usage visit https://github.com/OpenSLO/oslo/blob/main/examples/example.go
