### ISSUE TITLE
Be explicit about a month vs 30 days

### ISSUE THREAD

**Issue by alexewerlof** [OpenSLO/OpenSLO#267]
### Problem to solve

1 month is by far the most common compliance period (SLO window).

OpenSLO allows both `1M` and `30d`, for one month and 30 days respectively.

There's a slight but important difference between them because [not all months are exactly 30 days](https://en.wikipedia.org/wiki/Month).

In Georgian calendar:

| Order | Name      | Number of days           |
|-------|-----------|---------------------------|
| 1     | January   | 31                        |
| 2     | February  | 28, 29 in leap years      |
| 3     | March     | 31                        |
| 4     | April     | 30                        |
| 5     | May       | 31                        |
| 6     | June      | 30                        |
| 7     | July      | 31 (formerly Quinctilis)  |
| 8     | August    | 31 (formerly Sextilis)    |
| 9     | September | 30                        |
| 10    | October   | 31                        |
| 11    | November  | 30                        |
| 12    | December  | 31                        |

_There are other calendars like lunar calendars where a month is roughly 28 days but they can be modeled using `28d` or `4w` convention._

By extension the same problem exists for quarters (`Q`) and years (`Y`): a quarter isn't always 90 days and a year isn't always 365 days.

### Proposal

* Allow `XM|Q|Y` only on calendar bound compliance periods

| Acronym | Meaning | Calendar Bound only |
|---------|---------|----------------------|
| `m`     | Minutes | no|
| `h`     | Hours   | no                  |
| `d`     | Days    | no                  |
| `w`     | Weeks   | no (see #263) |
| `M`     | Months  | yes                  |
| `Q`     | Quarters| yes                  |
| `Y`     | Years   | yes                  |

**Comment by fourstepper** [comment]
I'm for fixed number values support in `duration` only - minutes, hours, days and weeks (as discussed on the OpenSLO meeting)
