### ISSUE TITLE
Document metrics and data sources

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#27]
Coming out of a discussion here https://github.com/OpenSLO/oslo/issues/31 we should document the decisions around metrics and data sources

**Comment by its02003** [comment]
Thanks for moving this, this was where I meant to ask it in the first place :)

**Comment by programmer04** [comment]
Does https://github.com/OpenSLO/OpenSLO/pull/178 affect the validity of this issue?
