### ISSUE TITLE
feat: Support JSON format in the Go SDK

### ISSUE THREAD

**Issue by fourstepper** [OpenSLO/OpenSLO#283]
There's nothing technically stopping us from supporting OpenSLO schema definitions using JSON.
For some languages/scenarios it is easier to use JSON, even for Go, it has native `encoding/json` package while YAML support is not included in the standard library.

We'll need to add `json` tags to all the structs as well as extend:
- https://github.com/OpenSLO/OpenSLO/blob/main/pkg/openslosdk/format.go
- https://github.com/OpenSLO/OpenSLO/blob/main/pkg/openslosdk/encoding.go

**Comment by nieomylnieja** [comment]
Done in https://github.com/OpenSLO/OpenSLO/pull/291.
