### ISSUE TITLE
Add Budget Adjustment Spec

### ISSUE THREAD

**Issue by thisisibrahimd** [OpenSLO/OpenSLO#302]
### Problem to solve

I would like to solve of problem of adjustment the SLI percentage when an accepted and expected event occurred that caused some dips in the SLI perf.

For example,
We have an uptime SLO for a service and we are expected to bring it down for a few minutes to upgrade it. Those minutes of downtime are acceptable to both users and operators but the SLI percentage does not recognize that. The only way to reflect that is notes in a SLA report but we would like to track the accepted downtime in a formal manner.

### Proposal

I would like to solve the problem by creating a  budget adjustment spec to track that.

### Further details

 n/a

### Links / references

PR: https://github.com/OpenSLO/OpenSLO/pull/301
Discussion: https://github.com/OpenSLO/OpenSLO/discussions/256
CLI Example: https://github.com/thisisibrahimd/opensloctl

**Comment by fourstepper** [comment]
I'm really not sure how I feel about this. On one hand, I understand what the issue that you are trying to solve is, on the other hand, I am not sure if it's job of the specification (or frankly implementations) to support use-cases such as this one. 

It would make more sense to me to solve your use-case at the monitoring level, for example by changing the uptime target or something similar (in the spirit of "it's agreed upon all people involved that this service should be considered 'up'")

I would love to hear from other contributors though.

**Comment by fourstepper** [comment]
Let's keep the discussion to the PR and re-open the issue if needed.
