### ISSUE TITLE
Create a shared demo app as a hello world for OpenSLO

### ISSUE THREAD

**Issue by metalmatze** [OpenSLO/OpenSLO#61]
### Problem to solve

We currently have many different examples floating around all the various projects. 

### Proposal

Let's come together and create a decent hello world example SLO based on real world data.

We could use the https://openslo.com/ website itself and export its metrics.
Another idea would be using the example from the "Implementing Service Level Objectives" book!
https://www.wienershirtzel.com/

_Note: Sorry for the typos, this issue was created during a live stream._

**Comment by proffalken** [comment]
I've started work on something that could easily morph into this, I just need to move it away from being AWS specific and into something that's more OTLP focused.

I'll try and find time to do that in the next week or so.

**Comment by ian-bartholomew** [comment]
Duplicates #44
