### ISSUE TITLE
allow ratioMetric to support single query

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#7]
Currently, the `ratioMetric` requires two separate queries, one for `good` responses, the other for `total`.  In some circumstances, it would be desirable to have a single query where good and total are inferred based on the query response.  The spec would need to support both the tallying of the total number, as well as mapping of the values to the appropriate group e.g. `true` maps to `good` and increments the total, and `false` simply maps to `total`

**Comment by steventhurgood** [comment]
A strong argument in favour of this is when your monitoring system collects, or derives, metrics at different times. If your numerator and denominator are not perfectly in sync, you run into issues like (number of good events) > (total number of events), and SLI performance outside the [0%, 100%] range, negative burn rates (we're *saving* error budget), and so on.
