### ISSUE TITLE
value should not be set when using ratioMetrics

### ISSUE THREAD

**Issue by ian-bartholomew** [OpenSLO/OpenSLO#8]
When using `ratioMetrics`, it doesn't make sense to include or require `objectives.value`, and should be removed

**Comment by joegalley** [comment]
What does `value` mean exactly? To me it reads the same as `target`

**Comment by geototti21** [comment]
@ian-bartholomew I am looking to pick this up but I am not entirely sure if `value` is needed for `thresholdMetric` or not needed at all.

I made a Draft PR to get some feedback here https://github.com/OpenSLO/OpenSLO/pull/56
